name: meta-biosensor
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.11
  - snakemake
  - fastp
  - megahit
  - prodigal
  - hmmer
  - pip
  - pip:
      - jsonapi-client
      - transformers>=4.30.0
      - torch>=2.0.0
      - biopython>=1.80
      - pandas>=2.0.0
      - numpy>=1.25.0
      - umap-learn
      - hdbscan
      - matplotlib>=3.7.0
      - seaborn>=0.12.0
      - tqdm>=4.66.0
      - scikit-learn>=1.3.0